### ISSUE TITLE
Just to clarify the kernel level here

### ISSUE THREAD

**Issue by Hasimir** [google/asylo#1]
In the quickstart example's description of an enclave it says:

> Enclaves are an emerging technology paradigm that changes this equation. An enclave is a special execution context where code can run protected from even the OS kernel, with the guarantee that even a user running with root privileges cannot extract the enclave's secrets or compromise its integrity. Such protections are enabled through hardware isolation technologies such as Intel SGX or ARM TrustZone, or even through additional software layers such as a hypervisor. These technologies enable new forms of isolation beyond the usual kernel/user-space separation.

Am I reading this correctly; that what you've effectively done is re-implemented a microkernel, except without the microkernel (i.e. it doesn't matter if it's a microkernel or a monolithic kernel under the hood)?

**Comment by deeglaze** [comment]
Asylo is not a microkernel and does not intend to be a microkernel. Certainly there are similarities, but our design does not intend to implement an entire operating system. The framework will implement some security-critical system calls itself, or simply pass through the call to the untrusted environment for the host OS to perform. The separation between trusted code (small, highly vetted, protected with encryption) and untrusted code (monolithic, majority non-sensitive computations) is a foundational idea in Asylo that is stricter than the requirements on a microkernel.

**Comment by deeglaze** [comment]
I'm closing this issue because it is not a bug or feature request.

Please use the [asylo-users@](https://groups.google.com/forum/#!forum/asylo-users) Google group or asylo tag on [Stack Overflow](https://stackoverflow.com/questions/tagged/asylo) in the future for such questions. We would like to reserve the GitHub issues space for bug reports and feature requests. User support is best delegated to those platforms.

Thank you for your interest in Asylo! We hope you enjoy your experimentation with the framework.

**Comment by Hasimir** [comment]
All right, that's a little more clear, thanks.

As for experimentation, [we](https://gnupg.org) may find a use for a container like this, particularly if the cryptographic component plays nicely with our own or with something else supported by libgcrypt, but we'll see.  No promises.
