### ISSUE TITLE
Address family not supported by protocol family","errno":106

### ISSUE THREAD

**Issue by tgamal** [google/asylo#20]
am trying to get this gRPC server example to work with Google Asylo (https://github.com/google/asylo/tree/master/asylo/examples/grpc_server).. To initialize the server I need to a specify a server_address in this config file (https://github.com/google/asylo/blob/master/asylo/examples/grpc_server/grpc_server_config.proto)

The server address in the example is written like this:

```
/ The address that the gRPC server inside the enclave will be hosted on.
 // Required.
optional string server_address = 205739939;
```

I am not sure what is the format of this address (i.e., is it IPv4 or Ipv6). When I try the address in the example it gives me the following error:

E0415 20:26:28.102505429 139772652978128 server_chttp2.cc:40] {"created":"@1555359988.102435497","description":"No address added out of total 1 resolved","file":"external/com_github_grpc_grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":348,"referenced_errors":[{"created":"@1555359988.102435497","description":"Address family not supported by protocol family","errno":106,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":379,"os_error":"Address family not supported by protocol family","syscall":"socket","target_address":"[::1]:0"}]} 2019-04-15 20:26:28 FATAL grpc_server_driver.cc : 62 : Load grpc_server/grpc_server_enclave.so failed: ::asylo::error::GoogleErrorSpace::INTERNAL: Failed to start server

I would like to write Ipv4 address for example: 127.0.0.1:5000 but I fail to do that. Any pointers are appreciated ?

**Comment by annasapek** [comment]
Are you getting this error when running [these commands](https://github.com/google/asylo/tree/master/asylo/examples/grpc_server#interacting-with-the-server) on the unmodified example? If not, can you let me know what command you ran and what version of Asylo you are using?

This example was written to require IPv6 so if your system doesn't support IPv6 (for instance, most default Docker installations do not), you would get this error. You can try changing `"[::1]:0"` to `"127.0.0.1:0"` in examples/grpc_server/grpc_server_driver.cc to see if that fixes the problem. We will update the example so that it can be used with systems that support only IPv4.

**Comment by tgamal** [comment]
Thanks @annasapek , the change you suggested solved my problem.
