### ISSUE TITLE
Does asylo only support C++ ？

### ISSUE THREAD

**Issue by MatthewShine** [google/asylo#25]
I am only familia with jave EE project。is it diffcult to use asylo for buliding a enclave env?

actually, we want run a python server with ML mode in enclave。 is asylo canbe a solution for this?

reading english is still diffcult for me . I dont know weather i should spend time on docs or not?

**Comment by deeglaze** [comment]
Yes, Asylo is C++ only for now.

**Comment by KeithMoyer** [comment]
@MatthewShine,

As @deeglaze mentioned, Asylo only supports C++ right now. This is not, however, an explicit goal of Asylo. Supporting additional languages would be something we would like to do; we just haven't been able to prioritize adding that support.

Python and Java, specifically, would add a layer of difficulty because the actual executable code is the interpreter / VM. The functional part is a payload that is run by that code, so the story for establishing a meaningful enclave identity / attestation becomes less straightforward.  It wouldn't be impossible, though, and it's something we'd like to look into eventually.
