### ISSUE TITLE
BUILD Files in /examples/

### ISSUE THREAD

**Issue by TitouanLazard** [google/asylo#4]
Hey,
I am not sure it is a real issue, but the examples provided in /examples/ can not be built. 
Bazel rises errors about the "enclave_loader" symbole which is not defined anywhere.

It works well if I use the BUILD file provided in "https://asylo.dev/asylo-examples.tar.gz", where "enclave_loader" is replaced by "debug_enclave_driver".
The BUILD file presented in "/examples/quickstart/README.md", also use "enclave_loader" instead of "debug_enclave_driver".

Is this "debug_enclave_driver" just a temporary symbole, which will be replaced by "enclave_loader" in the futur ? 

Regards,
Titouan

**Comment by KeithMoyer** [comment]
Thank you for reporting this issue.

The bazel macros recently underwent some refactoring (see commit 0e017848cc5ef89b6506d26a72ec1afec23bba4e), and `enclave_loader` is now the preferred rule to use.  `debug_enclave_driver` is marked as deprecated and will be removed at some point in the future.

The issue you report arises from the fact that the examples were written with the intent that they could be built completely separately from the Asylo source tree.  As such, the WORKSPACE file points to the latest release of the Asylo project to use it as a dependency.  However, while the examples were updated so that the next release would show them using the latest best-practice (`enclave_loader`), there hasn’t been such a next release for the WORKSPACE to reference.

There are a couple of ways this could be resolved to avoid this confusion, and it should be fixed sometime soon; in the meantime, though, using the examples directory from the v0.2.0 release ([asylo-examples.tar.gz](https://asylo.dev/asylo-examples.tar.gz) has content from that release) is probably your best bet.

**Comment by TitouanLazard** [comment]
Hi,

Thank you for the clarification.
Do I close the issue now ? Or I wait for the new WORKSPACE to be pushed ?

**Comment by KeithMoyer** [comment]
Titouan,

This is definitely still an issue.  Let's keep it open until a proper fix is submitted.

**Comment by KeithMoyer** [comment]
Note that with the 0.2.1 release that just occurred, the examples directory is directly buildable on the master branch again.

I would, however, like to keep this issue open until the project layout is change in such a way that this would not occur with any similar, future changes.

**Comment by KeithMoyer** [comment]
After 8d42b53cc784e804882a397d9e12dfb8c7782669 (included in Ayslo [0.2.2](https://github.com/google/asylo/releases/tag/v0.2.2)), the examples directory no longer attempts to use Asylo as an external resource.  Instead, it incorporates itself into the Asylo workspace, but still uses Bazel visibility to make sure it doesn't use any parts of Asylo that external clients couldn't use.
The [asylo-examples.tar.gz](https://asylo.dev/asylo-examples.tar.gz) file on the [asylo.dev](https://asylo.dev) website still illustrates how to use Asylo as an external dependency, but it is no longer an identical copy of the examples directory.

With this change, the examples directory should no longer be at risk of not being buildable as it's updated with changes not reflected in released versions of Asylo.  Closing this bug.
