### ISSUE TITLE
MAC verification failed

### ISSUE THREAD

**Issue by ipetr0v** [google/asylo#48]
I'm trying to use local attestation for an SGX enclave.
But when a local client connects to the enclave through gRPC, I got the following error on the client side (server side doesn't show any errors):
```
2019-11-19 14:03:07  ERROR  client_ekep_handshaker.cc : 307 : Assertion could not be verified: ::asylo::error::GoogleErrorSpace::INTERNAL: MAC verification failed
2019-11-19 14:03:07  ERROR  client_ekep_handshaker.cc : 307 : Assertion could not be verified: ::asylo::error::GoogleErrorSpace::INTERNAL: MAC verification failed
2019-11-19 14:03:07  ERROR  client_ekep_handshaker.cc : 99 : ::asylo::error::EkepErrorSpace::Bad assertion: Assertion could not be verified
2019-11-19 14:03:07  ERROR  client_ekep_handshaker.cc : 99 : ::asylo::error::EkepErrorSpace::Bad assertion: Assertion could not be verified
```

I have tried to debug this in `gdb` and got these results:
```gdb
(gdb) p/x actual_mac.data_
$8 = {0xe4, 0x66, 0x51, 0x28, 0x7e, 0x72, 0x45, 0x86, 0x4b, 0xeb, 0x1, 0x17, 0xa, 0x13, 0xc4, 0xc0}
(gdb) p/x report.mac.data_
$9 = {0x75, 0x8a, 0xfb, 0xaa, 0x6d, 0x1e, 0x8c, 0xa4, 0x4b, 0xa4, 0x24, 0x58, 0x15, 0x37, 0xf6, 0x7c}
```
in file:
https://github.com/google/asylo/blob/befb2efc1aa2bf6cf6f2ced869182ee3ce921817/asylo/identity/sgx/sgx_identity_util_internal.cc#L731-L733

So MACs are different, but I'm not sure why and how it could possibly be.
___
Here are main code snippets used in this example:

Enclave assertion initialization:
https://github.com/ipetr0v/oak/blob/2f2a7fec16529419c2c9f2b44b79cdf4c87fe638/oak/server/asylo/asylo_oak_manager.cc#L81-L91

Enclave channel creation:
https://github.com/ipetr0v/oak/blob/2f2a7fec16529419c2c9f2b44b79cdf4c87fe638/oak/server/oak_grpc_node.cc#L33-L43

Client assertion initialization:
https://github.com/ipetr0v/oak/blob/2f2a7fec16529419c2c9f2b44b79cdf4c87fe638/oak/client/application_client.h#L144-L160

Client channel creation:
https://github.com/ipetr0v/oak/blob/2f2a7fec16529419c2c9f2b44b79cdf4c87fe638/oak/client/application_client.h#L97-L99

**Comment by tiziano88** [comment]
@ipetr0v did you manage to dump the key too? I remember you found out the key id was something like `FF00FF00FF00...`, which may or may not be expected for a simulated / fake enclave.

**Comment by ipetr0v** [comment]
Yes, the key was as follows:
```gdb
(gdb) p/a report.keyid.data_
$19 = {0xff, 0x0, 0xff, 0x0, 0xff, 0x0, 0xff, 0x0, 0xff, 0x0, 0xff, 0x0, 0xff, 0x0, 0xff, 0x0 <repeats 17 times>}
```

**Comment by ipetr0v** [comment]
I have found this key in [linux-sgx](https://github.com/intel/linux-sgx)
```c++
/* The report key is the same as BASE_REPORT_KEY in
   /trunk/sdk/simulation/tinst/deriv.cpp, which is used in simulation
   create_report and verify_report. deriv.cpp is used inside enclave.
   So only import this structure. */
static const uint8_t BASE_REPORT_KEY[] = {
    0xff, 0x00, 0xff, 0x00, 0xff, 0x00, 0xff, 0x00,
    0xff, 0x00, 0xff, 0x00, 0xff, 0x00, 0xff, 0x00,
};
```
https://github.com/intel/linux-sgx/blob/d166ff0c808e2f78d37eebf1ab614d944437eea3/sdk/simulation/uae_service_sim/quoting_sim.cpp#L106-L113

**Comment by annasapek** [comment]
The problem is this:

> I'm trying to use local attestation for an SGX enclave...

> ...a local client connects to the enclave through gRPC

SGX local attestation only works between enclaves because it relies on symmetric secrets baked into the hardware, or in this case the simulation of hardware. SGX enclaves get access to those secrets through EGETKEY and EREPORT but non-SGX-enclaves cannot issue those instructions. This means that non-SGX enclaves cannot even _verify_ SGX local assertions.

I admit that the results here look misleading since both participants are generating SGX local assertions, exchanging them, and attempting to verify their peer's assertion. Your client, which is not an enclave, is actually using [fake_hardware_interface.cc](https://github.com/google/asylo/blob/master/asylo/identity/sgx/fake_hardware_interface.cc), which implements the EREPORT and EGETKEY functionality in software. Of course, SGX-simulation does something similar (and you found the base REPORT key). However, the implementations don't agree on the root key material so they are not inter-operable.

There's basically three flavors of SGX local attestation you can get with Asylo:

- **Fake**, backed by Asylo's fake_hardware_interface.cc
- **Simulated**, backed by Intel's SGX simulation from the Linux SGX SDK
- **Real**, backed by actual SGX hardware

However, SGX local attestation will only work between two enclaves of the same type, so you can't mix **Fake** and **Simulated**. You can't mix with **Real** with **Simulated** or **Fake** either, although that's probably a little more obvious.

Other users have run into similar problems so it is probably worth it for us to look into how we can prevent users from accidentally creating similar setups. We may end up not exposing the **Fake** SGX local attestation to users, since it's really for Asylo's internal testing.

**Comment by ipetr0v** [comment]
@annasapek thanks for your answer!

**Comment by tiziano88** [comment]
@annasapek what's preventing a random enclave from running and exporting the symmetric key used to verify the attestation? Or is it just an id / pointer to an unexportable key that can only be used for crypto operations with hardware support?

**Comment by annasapek** [comment]
I slightly oversimplified in my previous comment. EGETKEY only gives an enclave access to its own REPORT key, which is derived from the root key material and has properties of the enclave's identity  mixed in. Therefore, an enclave can only compromise its own REPORT key and not the platform's root secrets. That's also why non-enclaves can't invoke EGETKEY; there are no bits of the identity to mix in for non-enclaves.

This explains why with SGX hardware it is not possible for one enclave to compromise the platform's secrets. In the fake and simulated cases, the root keys are hard-coded values that anyone can obtain.

**Comment by tiziano88** [comment]
My point is: can we write an enclave that gets its own key from the CPU and prints it out to a file, and then keep using it from then on to keep verifying assertions outside of other enclaves? Or, for this specific case of the server using an sgx simulated enclave, can we pass the hardcoded key directly to the verifier? Don't worry, we don't have a real use case for this, but it may be a stop gap solution to verify attestations until we get remote attestation in Asylo.

**Comment by annasapek** [comment]
In theory, yes, that should work... Asylo's `SgxLocalAsssertionVerifier` wouldn't allow that though. You'd have to write a custom verifier that uses a hard-coded key for verifying Assertions, and a hard-coded TARGETINFO in its AssertionRequests.

**Comment by ipetr0v** [comment]
@annasapek there is also an entity used in the local attestation - called the **Attestation Domain**. Code comments say that it should be a 16-byte string.
https://github.com/google/asylo/blob/676b9f3f86dace43755d452b016c8cac14a69df0/asylo/identity/enclave_assertion_authority_configs.h#L71-L79

Should this domain be a shared secret between two enclaves, that want to attest each other?
Or it's just a convenience public string, that is used to search for enclaves created by the same party?

**Comment by annasapek** [comment]
The attestation domain is a convenience string that it used to identify if two enclaves are on the same machine and can use SGX local attestation. It's a public value, and it's not added for security, just for optimizing the handshake. If you use the attestation domain on two different SGX machines, then you will just end up getting the MAC verification error again.
