### ISSUE TITLE
generate_sigstruct is not generating SIGSTRUCT

### ISSUE THREAD

**Issue by ipetr0v** [google/asylo#51]
The Bazel rule `sgx.generate_sigstruct`, that is defined here:
https://github.com/google/asylo/blob/361737de928acbd01a6ca206292bf79c0484c62b/asylo/distrib/sgx_x86_64/linux_sgx_2_6.patch#L5420

https://github.com/google/asylo/blob/361737de928acbd01a6ca206292bf79c0484c62b/asylo/distrib/sgx_x86_64/linux_sgx_2_6.patch#L5136-L5170

is not generating an actual `SIGSTRUCT` (generating some other structure), because the parameter `gendata` uses only `header` and `body` (without including `key` and `buffer` that are also presented in `SIGSTRUCT`) as shown here:
https://github.com/intel/linux-sgx/blob/d10cabebb5512878e84f5d21cdf27c39c428ffe2/sdk/sign_tool/SignTool/sign_tool.cpp#L528-L548

with the SIGSTRUCT definition here:
https://github.com/intel/linux-sgx/blob/d10cabebb5512878e84f5d21cdf27c39c428ffe2/common/inc/internal/arch.h#L240-L245

![image](https://user-images.githubusercontent.com/9150926/69369986-f1d23600-0c94-11ea-942d-a726a6b03489.png)

**Comment by deeglaze** [comment]
Yes this is by design. SIGSTRUCT is self-referential because it contains a signature of parts of the rest of the SIGSTRUCT (header and body, by sgx sdk's struct type). That "rest of the sigstruct" is what `sgx_generate_sigstruct` produces, because that's what needs to be SHA256-signed. `sgx_signed_enclave` consumes the signature, the signing key's public key, the "rest of sigstruct" file, and the unsigned binary to produce an enclave binary that has the entire SIGSTRUCT assembled and put in the right place for loading.
 
The rule's name is semi-misleading because it isn't an entire `enclave_css_t` (linux_sgx sgx sdk type defined in arch.h) object, I agree. There was no good name for it. I considered `sgx_generate_signing_material` but that was too vague and too long. Do you have a recommendation?

**Comment by tiziano88** [comment]
I agree that the name is not ideal and in fact we spend more time than we would like to admit trying to figure out why the offsets from the official Intel documentation would not match the output of the `generate_sigstruct` rule, given it claims to generate a `SIGSTRUCT`.

To avoid further confusion, I would strongly recommend renaming that to `generate_enclave_signing_material` (in line with the terminology used in the `sgx_sign_tool`) or similar.

**Comment by tiziano88** [comment]
Also, it seems problematic to just be signing an opaque blob of data without understanding what it contains; we would like to be able to inspect / pretty print the contents of the signing material if possible, is there any tool that does that already? If not, I guess for now we can manually figure out the offsets of the pieces of data we are interested in (`MRENCLAVE`, `ATTRIBUTES`, etc.) and print them out one by one, but I hope there is (or will be) a nicer solution.

**Comment by deeglaze** [comment]
I've added a new rule with an appropriate name and deprecated the old rule. I'm working on a script that will overlay colors on a hexdump to explain the various pieces.

**Comment by tiziano88** [comment]
Wow thanks for the quick fix @deeglaze , much appreciated! And looking forward to that script. If possible, could you also make it print a list of key: value pairs or a JSON file, which would be more accessible and easier to copy around (e.g. in an email message or GItHub issue)? Of course having the terminal-based color output as an extra would be neat too :)

**Comment by deeglaze** [comment]
@tiziano88 You can see the script here https://gist.github.com/deeglaze/a8f0f982bc1e4d17c38cf9571d15fd37
Although it's under review, you can play with it and tell me what you think.

**Comment by tiziano88** [comment]
Thanks @deeglaze the script looks like it would do the job, but I personally would not look forward to maintaining a shell script more than a few lines long. Especially since it is mostly about parsing and printing stuff out, things for which having actual types and libraries is usually helpful :) My suggestion would be to create a small Rust (though this is frowned upon in Google) or C++ binary, and let it do the job. Note also that the intel SDK contains the actual structs used to generate the signing material, so it may make sense to just link against that, parse the file, and print out the individual fields. WDYT?
