### ISSUE TITLE
Mitigations / software hardening for LVI?

### ISSUE THREAD

**Issue by tomtau** [google/asylo#59]
https://software.intel.com/security-software-guidance/insights/deep-dive-load-value-injection#applysgxmitigation

Some part of it should be handled by the patched LLVM:  https://reviews.llvm.org/D75938
but that may not cover e.g. BoringSSL assembly code

**Comment by iKevinY** [comment]
Thank you for bringing this to our attention @tomtau! Due to toolchain complexity, it took a little longer than expected to integrate these mitigations into Asylo, but they are in as of 9d43b6c4660553c1839d4972fbdcf07dd4e1dc62. Since Asylo uses GCC rather than Clang, we pulled Intel’s upstream Binutils patch (bminor/binutils-gdb@ae53104) into our toolchain, and extended Bazel to allow for varying levels of mitigation to be set.

By default, enclaves will now be built with the most aggressive level of LVI mitigation (Intel’s “all loads mitigation”). This can be tweaked in two ways: firstly, by specifying a different “mitigation feature” within the `transitive_features` attribute of an unsigned enclave target (valid options are `lvi_control_flow_mitigation` and `lvi_no_auto_mitigation`:

```bazel
cc_unsigned_enclave(
    name = "foo_enclave_unsigned.so",
    srcs = ["foo_enclave.cc"],
    transitive_features = ["lvi_control_flow_mitigation"],
)
```
Or by passing the `--features=lvi_*_mitigation` flag to a Bazel command line invocation.
